notifications:
    email: false
sudo: false

language: node_js
node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8 TEST_DIR=server

script: cd $TEST_DIR && npm install && npm test
